services:
  qdrant:
    image: "qdrant/qdrant:latest"
    container_name: "mem0-qdrant"
    restart: always
    volumes:
      - qdrant_data:/qdrant/storage:z
    ports:
      - "6333:6333"
      - "6334:6334"

  neo4j:
    image: neo4j:5.15.0
    container_name: "mem0-neo4j"
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/voiceflow
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_server_config_strict__validation_enabled=false
    volumes:
      - neo4j_data:/data
      - ./neo4j/plugins:/plugins
    healthcheck:
      test: ["CMD-SHELL", "neo4j status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  mem0:
    container_name: "mem0"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "4321:5000"
    depends_on:
      qdrant:
        condition: service_started
      neo4j:
        condition: service_healthy
    environment:
      - QDRANT_HOST=qdrant
      - NEO4J_HOST=neo4j
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=voiceflow

volumes:
  qdrant_data:
    driver: local
  neo4j_data:
    driver: local
